version: '3'

tasks:

  install_dependencies:
    - pip install poetry

  install:
    - poetry install

  code_formating:
    - poetry run black shaclgen tests

  code_formating_check:
    - poetry run black --check shaclgen tests

  test:
    - poetry run pytest -rP --cov=shaclgen --cov-report=term-missing

  ci:
    cmds:
      - task: install_dependencies
      - task: install
      - task: test
      - task: code_formating_check

# Aliases
#
# Should be new syntax onece v4 is out:
# https://github.com/go-task/task/issues/675

  black:
    - task: code_formating
