version: '3'

tasks:

  install_dependencies:
    cmds:
      - pip install poetry

  install:
    cmds:
      - poetry install

  code_formating:
    cmds:
      - poetry run black shaclgen tests

  test:
    cmds:
      - poetry run pytest --cov=shaclgen --cov-report=term-missing

  ci:
    cmds:
      - task: install_dependencies
      - task: install
      - task: test
